<a href="https://colab.research.google.com/github/SANTONLA/NUMPY/blob/main/04_Ejercicios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![logo.png](attachment:logo.png)

#### Módulo 1: Python para la ciencia de datos

# Ejercicios NumPy

In [1]:
import numpy as np

### Ejercicio 1
Una vez importado numpy, crea un array numpy a partir de la siguiente lista. Muestra por pantalla el tipo de dicha lista, el número de dimensiones que tiene y cuántos elementos hay por dimensión

In [2]:
lista=[100,80,180,140,25,170,200]

array=np.array(lista)
print("Tipo de datos: {}".format(array.dtype))
print("Numero de dimensiones: {}".format(array.ndim))
print("Tamaño de las dimensiones: {}".format(array.shape))
print("Numero de elementos: {}".format(array.size))
print()
print("Función del módulo numpy")
print("Numero de dimensiones: {}".format(np.ndim(array)))
print("Tamaño de las dimensiones: {}".format(np.shape(array)))

print("Tipo de datos: {}".format(array.dtype))
print("Numero de dimensiones: {}".format(array.ndim))


Tipo de datos: int64
Numero de dimensiones: 1
Tamaño de las dimensiones: (7,)
Numero de elementos: 7

Función del módulo numpy
Numero de dimensiones: 1
Tamaño de las dimensiones: (7,)
Tipo de datos: int64
Numero de dimensiones: 1


In [3]:
lista = [100, 80, 180, 140, 25, 170, 200]

### Ejercicio 2
Realiza la misma operación pero ahora sobre esta matriz. Imprime el número de dimensiones y cuántos elementos hay

In [4]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
matriz2=np.array(matriz)
print("Segunda versión de matriz2:")
print("Tipo de datos: {}".format(matriz2.dtype))
print("Numero de dimensiones: {}".format(matriz2.ndim))
print("Tamaño de las dimensiones: {}".format(matriz2.shape))
print("Tipo de datos: {}".format(matriz2.dtype))
print("Numero de elementos: {}".format(matriz2.size))

Segunda versión de matriz2:
Tipo de datos: int64
Numero de dimensiones: 2
Tamaño de las dimensiones: (3, 3)
Tipo de datos: int64
Numero de elementos: 9


### Ejercicio 3

Dada la siguiente matriz, transformarla en una matriz numpy y hacer un recorrido para que muestre:

el valor de la posición (0,0) es 1

el valor de la posición (0,1) es 2

...

In [6]:
matriz2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]]

In [7]:
npmatriz=np.array(matriz2)

In [8]:
print(npmatriz[0][0])

1


In [ ]:
print(npmatriz[0,1])

2


### Ejercicio 4

Crear una matriz numpy de ceros de 5 filas y 4 columns

Crear una matriz numpy de unos de 10 filas y 10 columnas

Crear un vector numpy con los numeros del 0 al 1000

In [9]:

c=np.zeros((5,4))

print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:

a=np.ones((10,10))
print(a)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### Ejercicio 5

Crear una matriz a de números aleatorios de 4 filas y 3 columnas. Crear una nueva matriz b con los mismos elementos pero en forma de 6 filas y 2 columnas (utilizando reshape). Modificar el elemento (0,0) de b poniéndolo a 0 y mostrar a por pantalla.

In [11]:
o=np.random.rand(4,3)

print(o)


[[0.64879025 0.21023311 0.43175298]
 [0.83258559 0.96114489 0.34438431]
 [0.72114697 0.15801534 0.60024092]
 [0.61709711 0.21335924 0.46303875]]


In [12]:
o=np.random.rand(4,3)
print(o.reshape((6,2)))
print(np.reshape(o,(6,2)))
print(o)

[[0.89749786 0.17399911]
 [0.43086639 0.20320172]
 [0.24088307 0.28814384]
 [0.85939077 0.0643251 ]
 [0.31846132 0.46957502]
 [0.03939054 0.09831206]]
[[0.89749786 0.17399911]
 [0.43086639 0.20320172]
 [0.24088307 0.28814384]
 [0.85939077 0.0643251 ]
 [0.31846132 0.46957502]
 [0.03939054 0.09831206]]
[[0.89749786 0.17399911 0.43086639]
 [0.20320172 0.24088307 0.28814384]
 [0.85939077 0.0643251  0.31846132]
 [0.46957502 0.03939054 0.09831206]]


### Ejercicio 6

Dada la siguiente lista, transformarla en un array numpy. Muestra el número de dimensiones. A continuación transfórmalo en un vector columna. Muestra el número de dimensiones

In [13]:
lista = [100, 80, 180, 140, 25, 170, 200]

In [14]:
a=np.array(lista)

In [15]:
print("Tamaño de las dimensiones: {}".format(a.shape))

Tamaño de las dimensiones: (7,)


In [16]:
print(a.reshape((7,1)))

[[100]
 [ 80]
 [180]
 [140]
 [ 25]
 [170]
 [200]]


### Ejercicio 7

Intenta repetir el mismo ejercicio que el 5 pero utilizando la función resize. Observa que la función resize modifica las propias dimensiones de a

In [17]:
o=np.random.rand(4,3)
print(o.resize((6,2)))
print(np.resize(o,(6,2)))
print(o)

None
[[0.95161497 0.05128991]
 [0.87071016 0.41079429]
 [0.36660322 0.15148545]
 [0.25785484 0.54340558]
 [0.55143103 0.39132593]
 [0.28541705 0.27184527]]
[[0.95161497 0.05128991]
 [0.87071016 0.41079429]
 [0.36660322 0.15148545]
 [0.25785484 0.54340558]
 [0.55143103 0.39132593]
 [0.28541705 0.27184527]]


### Ejercicio 8

Crear una matriz a de números aleatorios de 4 filas y 3 columnas. Crear un array b (una sola dimensión) con la concatenación de los elementos de a (utilizando ravel). Cambia el primer elemento poniéndolo a 0 y muestra a

In [18]:
o=np.random.rand(4,3)

print(o)

[[0.90686841 0.80147802 0.78619158]
 [0.30737705 0.42046755 0.43213643]
 [0.22869438 0.42427868 0.52023113]
 [0.93051166 0.76422293 0.36954649]]


In [19]:
a=np.array(o)
b=a.ravel()
print(a)
print(b)
b[0]=0
print(a)
print(b)





[[0.90686841 0.80147802 0.78619158]
 [0.30737705 0.42046755 0.43213643]
 [0.22869438 0.42427868 0.52023113]
 [0.93051166 0.76422293 0.36954649]]
[0.90686841 0.80147802 0.78619158 0.30737705 0.42046755 0.43213643
 0.22869438 0.42427868 0.52023113 0.93051166 0.76422293 0.36954649]
[[0.         0.80147802 0.78619158]
 [0.30737705 0.42046755 0.43213643]
 [0.22869438 0.42427868 0.52023113]
 [0.93051166 0.76422293 0.36954649]]
[0.         0.80147802 0.78619158 0.30737705 0.42046755 0.43213643
 0.22869438 0.42427868 0.52023113 0.93051166 0.76422293 0.36954649]


### Ejercicio 9

Crear una matriz a de números aleatorios de 4 filas y 3 columnas. Crear un array b (una sola dimensión) con la concatenación de los elementos de a. Suma 1 a todos los elementos del array b de tal forma que los valores de a no cambien.

In [20]:

# Crear matriz aleatoria de 4 filas y 3 columnas
a = np.random.rand(4, 3)

# Crear array unidimensional con la concatenación de los elementos de a
b = a.flatten()

# Sumar 1 a todos los elementos del array b
b += 1

# Imprimir la matriz original y el array modificado
print("Matriz a:")
print(a)
print("\nArray b (modificado):")
print(b)


Matriz a:
[[0.60445077 0.94353606 0.46782441]
 [0.46441332 0.1561649  0.01665125]
 [0.03547341 0.29278538 0.70226632]
 [0.3003743  0.79633249 0.62518659]]

Array b (modificado):
[1.60445077 1.94353606 1.46782441 1.46441332 1.1561649  1.01665125
 1.03547341 1.29278538 1.70226632 1.3003743  1.79633249 1.62518659]


### Ejercicio 10

Dada una matriz de unos de dimensión 10x10, modificar de una sola vez a 0 todos los elementos que no estén en el borde de la matriz (primera o última fila o columna).

In [21]:


# Crear una matriz de unos de dimensión 10x10
matriz = np.ones((10, 10))

# Modificar todos los elementos que no estén en el borde de la matriz a 0
matriz[1:-1, 1:-1] = 0

# Imprimir la matriz modificada
print(matriz)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### Ejercicio 11

Dada una matriz de unos de dimensión 8x8, modificar (en dos instrucciones) a 0 los elementos necesarios hasta crear una matriz de unos y ceros salteados (tipo tablero de ajedrez)

In [22]:


# Crear una matriz de unos de dimensión 8x8
matriz = np.ones((8, 8))

# Modificar los elementos pares a 0 en las filas y columnas pares
matriz[::2, ::2] = 0

# Modificar los elementos impares a 0 en las filas y columnas impares
matriz[1::2, 1::2] = 0

# Imprimir la matriz resultante
print(matriz)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### Ejercicio 12

Dada la siguiente matriz, obtener un array numpy con los elementos mayores de 10

In [23]:
matriz = [[ 0, 10, 20], [20, 30, 40]]

In [25]:

# Definir la matriz como una lista de listas
matriz = [[0, 10, 20], [20, 30, 40]]

# Convertir la matriz en un array numpy
matriz_np = np.array(matriz)

# Obtener un array numpy con los elementos mayores de 10
elementos_mayores_de_10 = matriz_np[matriz_np > 10]

# Imprimir el array resultante
print(elementos_mayores_de_10)


[20 20 30 40]


### Ejercicio 13
Dada la siguiente matriz, obtener una nueva en la que sumamos +1 a todos los elementos positivos y restamos 1 a todos los negativos

In [27]:
matriz = np.random.randn(10,10)
# Convertir la matriz en un array numpy
matriz_np = np.array(matriz)

In [28]:

# Aplicar la lógica para sumar 1 a los elementos positivos y restar 1 a los negativos
nueva_matriz = np.where(matriz > 0, matriz + 1, matriz - 1)

# Imprimir la nueva matriz
print(nueva_matriz)


[[ 1.11122594 -1.88445198 -1.12613773  1.69749097 -1.51894659 -1.12230967
  -1.48250903  1.1020847  -1.44538116 -1.79443508]
 [-2.1087261  -2.41518355 -2.40699631  1.97371097  1.27386732  2.87828518
  -1.35130439  1.48035201 -2.29191339 -1.97809233]
 [-2.01231828 -1.18636865  1.87205655  1.37343058  2.46838203  2.60972909
  -1.02572788  2.5027967  -1.87701165 -1.88212267]
 [ 2.17108889  1.85353846  1.73819038  2.03075319 -2.31382521 -1.12134277
   1.55869648 -1.19448168 -1.8607057  -1.41061947]
 [ 2.0049023   2.54257189 -1.45992154 -2.19239311  3.71709436 -1.5008661
  -1.01830603 -1.18837164  2.21205657  1.76129286]
 [-2.2599078   1.17022021 -2.91117312  1.77215603  1.74860634  1.14360633
  -1.02317582  3.97401568 -2.91570161  2.65021481]
 [-1.04651546  1.28863138 -1.77848969  3.60215505 -1.24564395  1.30362967
  -1.10504102  1.21979799  1.61164171 -3.04910178]
 [-1.19463595 -2.04518549 -1.59696006  1.2638245   1.16125927 -1.09362415
  -2.06335221  2.20528665  1.62146101  2.55762076]
 

### Ejercicio 14

Dada una matriz de dimensión 10x10 de números aleatorios siguiendo una distribución normal, sumar todos los elementos positivos, todos los negativos y todos los elementos de dicha matriz

In [29]:

# Generar una matriz de dimensión 10x10 de números aleatorios con distribución normal
matriz = np.random.normal(size=(10, 10))

# Calcular la suma de todos los elementos positivos
suma_positivos = np.sum(matriz[matriz > 0])

# Calcular la suma de todos los elementos negativos
suma_negativos = np.sum(matriz[matriz < 0])

# Calcular la suma de todos los elementos de la matriz
suma_total = np.sum(matriz)

# Imprimir los resultados
print("Suma de elementos positivos:", suma_positivos)
print("Suma de elementos negativos:", suma_negativos)
print("Suma total de la matriz:", suma_total)


Suma de elementos positivos: 30.422209876581487
Suma de elementos negativos: -33.0269051520754
Suma total de la matriz: -2.6046952754939086


### Ejercicio 15
Dada un array numpy con los números del 0 al 100, obtener la suma de los números que sean multiplos de 3 y de 5

In [30]:

# Generar un array numpy con los números del 0 al 100
array_numeros = np.arange(101)  # El límite superior se establece en 101 para incluir el 100

# Seleccionar los números que son múltiplos de 3 y de 5
multiplos_3_y_5 = array_numeros[(array_numeros % 3 == 0) & (array_numeros % 5 == 0)]

# Calcular la suma de los números que son múltiplos de 3 y de 5
suma_multiplos_3_y_5 = np.sum(multiplos_3_y_5)

# Imprimir la suma
print("La suma de los números que son múltiplos de 3 y de 5 es:", suma_multiplos_3_y_5)


La suma de los números que son múltiplos de 3 y de 5 es: 315


### Ejercicio 16

Dada una matriz de dimensión 100x5 de números aleatorios entre 0 y 1, obtener la suma de cada fila, la suma de cada columna y la suma de todos sus elementos

In [31]:

# Generar una matriz de dimensión 100x5 de números aleatorios entre 0 y 1
matriz = np.random.rand(100, 5)

# Calcular la suma de cada fila
suma_filas = np.sum(matriz, axis=1)

# Calcular la suma de cada columna
suma_columnas = np.sum(matriz, axis=0)

# Calcular la suma de todos los elementos
suma_total = np.sum(matriz)

# Imprimir los resultados
print("Suma de cada fila:", suma_filas)
print("Suma de cada columna:", suma_columnas)
print("Suma total de todos los elementos:", suma_total)


Suma de cada fila: [2.23035099 3.39938177 1.5926527  3.01019741 2.73167451 2.23276035
 4.16800246 3.33512006 2.71668535 2.63578879 2.58165719 1.7550997
 2.45116605 3.08475685 3.57082427 1.43799156 2.47915096 2.1780759
 2.36160602 1.57308783 2.97921015 1.62121764 2.11146223 2.23379244
 2.891776   2.47289001 2.81223673 2.75319863 3.7836587  2.32571542
 3.31755152 2.16574369 3.44326164 3.0369874  2.74898506 3.06679163
 2.01387633 2.11192522 2.74254653 4.15343085 3.52889093 2.54349046
 1.78389933 2.65961581 2.50595933 3.58880973 1.94676934 3.19037566
 2.6411491  1.50287685 2.74349089 2.96803796 1.61782161 2.34070997
 2.66280226 2.24063982 3.23276173 1.82355843 2.5030422  2.17579963
 2.74408738 2.69507142 3.3520322  3.17557367 3.28528783 2.23664017
 2.34193987 1.83326574 1.76693308 3.50893954 2.64764067 2.57586929
 2.99421808 2.42482455 3.40621997 1.91204796 3.01722218 1.92814432
 2.08476759 2.09772134 1.39462654 1.49703761 3.87151539 3.08716308
 3.65791722 3.08574713 3.37602194 2.20861617 

### Ejercicio 17

Dado un vector de 100 números aleatorios entre 0 y 1, cambiar el elemento más pequeño por un 0

In [32]:

# Generar un vector de 100 números aleatorios entre 0 y 1
vector = np.random.rand(100)

# Encontrar el índice del elemento más pequeño
indice_minimo = np.argmin(vector)

# Cambiar el elemento más pequeño por un 0
vector[indice_minimo] = 0

# Imprimir el vector modificado
print("Vector con el elemento más pequeño cambiado por 0:")
print(vector)


Vector con el elemento más pequeño cambiado por 0:
[0.86569348 0.35515796 0.34472268 0.15752826 0.93725006 0.68049898
 0.81299523 0.51970612 0.53470065 0.30806237 0.83949548 0.30696688
 0.72054393 0.63491133 0.49222192 0.67189051 0.57267125 0.88280051
 0.44789869 0.67425942 0.50558125 0.99788949 0.05446472 0.2919087
 0.60524274 0.61888003 0.6857247  0.31358872 0.30567489 0.02039039
 0.40807564 0.82765357 0.56874751 0.62244694 0.3832412  0.88791086
 0.86799926 0.28639022 0.74521184 0.19057859 0.37558043 0.92815591
 0.04662979 0.60960833 0.51451033 0.60683443 0.65215195 0.9297845
 0.90258724 0.88678051 0.71732915 0.05553176 0.29510788 0.4092429
 0.74203232 0.35774476 0.32514314 0.93558571 0.31338613 0.91477374
 0.69969497 0.03952358 0.8304853  0.53071699 0.01777769 0.83434929
 0.23219375 0.         0.59471526 0.48188495 0.03896372 0.1450843
 0.69604092 0.11879584 0.02443754 0.1334558  0.04089699 0.0644763
 0.95377097 0.95631234 0.9125415  0.82807842 0.70101478 0.36990538
 0.88095623 0.17

### Ejercicio 18

Crea dos matrices, a y b, de números aleatorios entre 0 y 1 de dimensión 10x10. Obtén una nueva matriz como resultado de sumar las dos matrices a y b

In [33]:


# Crear las matrices a y b de números aleatorios entre 0 y 1 de dimensión 10x10
a = np.random.rand(10, 10)
b = np.random.rand(10, 10)

# Obtener una nueva matriz como resultado de sumar las matrices a y b
nueva_matriz = a + b

# Imprimir la nueva matriz
print("Matriz resultante de la suma de a y b:")
print(nueva_matriz)


Matriz resultante de la suma de a y b:
[[0.64104972 0.43539391 0.93416246 1.4218376  1.32188543 0.91704538
  0.59670931 0.14131998 1.05079533 0.94314955]
 [0.74812586 0.86025221 0.45224958 1.76552711 1.82473036 1.13528408
  1.52540637 0.65101604 1.01411709 0.59712226]
 [0.68656764 0.76155664 0.46355262 0.95672013 1.37022278 0.60365094
  0.9434908  0.23815686 0.98323039 0.76711665]
 [0.84962322 1.07581839 1.03530653 0.82071937 0.54623041 0.81160732
  0.72896117 1.81240934 0.82466156 0.62033642]
 [1.55521803 1.18968967 0.20859162 1.38954798 1.14076315 1.34616369
  0.71621269 1.64835499 0.3753053  0.92942032]
 [0.9748112  1.26258857 1.31418805 1.14835808 1.52955475 0.99640626
  0.7687284  0.63832937 1.07993673 0.44746399]
 [1.70515066 1.38948544 1.32069655 0.53876772 0.40606326 1.29523456
  0.7996354  1.71557282 0.67460169 0.71971219]
 [0.98045498 1.32233698 1.06819607 0.83718079 1.19944608 0.78094905
  0.58586674 1.34035705 1.28118307 0.73019305]
 [1.09080363 1.41691362 0.69842358 0.8673

### Ejercicio 19

Dados la siguiente matriz y el vector, obtener una nueva matriz cuyos elementos sean el resultado de multiplicar elemento a elemento el vector fila por todas las filas de la matriz.

Obtener otra matriz cuyo resultado sea el de multiplicar elemento a elemento el vector por todas las columnas de la matriz

In [ ]:
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = [1, 2, 3]

In [34]:

# Multiplicar elemento a elemento el vector por todas las filas de la matriz
matriz_fila = a * b

# Multiplicar elemento a elemento el vector por todas las columnas de la matriz
matriz_columna = a * b[:, np.newaxis]

# Imprimir las matrices resultantes
print("Matriz resultado de multiplicar elemento a elemento el vector por todas las filas de la matriz:")
print(matriz_fila)

print("\nMatriz resultado de multiplicar elemento a elemento el vector por todas las columnas de la matriz:")
print(matriz_columna)


Matriz resultado de multiplicar elemento a elemento el vector por todas las filas de la matriz:
[[3.59968473e-02 2.09148847e-02 2.17445667e-01 4.78959811e-01
  4.35352894e-01 1.24604725e-01 7.07156487e-02 2.72900196e-04
  1.16152155e-01 1.59367127e-01]
 [1.24872279e-01 1.82954822e-01 3.52144465e-02 7.71607764e-01
  8.31801178e-01 3.21787914e-01 5.68082459e-01 2.17706482e-02
  2.33555380e-01 1.50567986e-02]
 [8.34932521e-02 1.44992127e-01 5.23289386e-02 2.28290007e-01
  4.22997508e-01 7.85512716e-02 2.18544585e-01 7.57991699e-03
  7.09827984e-02 1.46904383e-01]
 [1.46746911e-01 1.56623926e-01 2.03361029e-01 1.24615829e-01
  6.84845869e-02 1.64530875e-01 1.04722977e-01 8.21188412e-01
  1.18372600e-01 9.52281177e-02]
 [6.04407770e-01 2.71691770e-01 4.40513667e-03 4.63764935e-01
  2.91326105e-01 4.37395591e-01 9.27296296e-02 6.78059016e-01
  9.40231286e-03 1.56747240e-01]
 [2.02914513e-01 2.66458839e-01 3.47428810e-01 1.91053369e-01
  5.77352601e-01 1.05972363e-01 1.27178058e-01 5.02111321

### Ejercicio 20
Dadas las siguientes matrices, a y b, obtener el número de dimensiones de cada una de ellas. Obtener una nueva matriz c de forma se sume la matriz b a cada "capa" de la matriz a

In [35]:
a = np.random.rand(4,3,3)
b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])

In [38]:

# Definir las matrices a y b
a = np.random.rand(4, 3, 3)
b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])

# Ajustar las dimensiones de la matriz b para que coincida con las dimensiones de la matriz a
b_expandida = np.expand_dims(b, axis=0)  # Añadir una dimensión al principio

# Sumar la matriz b a cada "capa" de la matriz a
c = a + b_expandida

# Imprimir la nueva matriz c
print("Matriz resultante (c) después de sumar la matriz B a cada capa de la matriz A:")
print(c)



Matriz resultante (c) después de sumar la matriz B a cada capa de la matriz A:
[[[1.70820736 1.18627776 1.61505942]
  [2.68384909 2.23938479 2.59349564]
  [3.75335272 3.90867118 3.71509124]]

 [[1.07473205 1.90737048 1.90845389]
  [2.82882731 2.93450236 2.90640035]
  [3.59171629 3.89289566 3.50928989]]

 [[1.50096641 1.01660054 1.74108172]
  [2.67672588 2.88213266 2.12959873]
  [3.79756853 3.93272237 3.2242953 ]]

 [[1.62900018 1.67603687 1.15363226]
  [2.63097934 2.88354149 2.67297139]
  [3.74228609 3.63307208 3.0572451 ]]]


### Ejercicio 21

Dados los siguientes vectores a y b, obtener una matriz c de tal forma que $c_{ij} = a_i \times b_j$

In [ ]:
a = [1, 2, 3]
b = [1, 2, 3]

In [39]:
# Definir los vectores a y b
a = [1, 2, 3]
b = [1, 2, 3]

# Obtener la matriz c usando np.outer
c = np.outer(a, b)

# Imprimir la matriz c resultante
print("Matriz c:")
print(c)


Matriz c:
[[1 2 3]
 [2 4 6]
 [3 6 9]]


### Ejercicio 22

Crear una matriz 3x3 con todos los valores del rango [0,8].

In [40]:

# Crear un array de 0 a 8 (inclusive)
valores = np.arange(9)

# Remodelar el array en una matriz 3x3
matriz = valores.reshape(3, 3)

# Imprimir la matriz resultante
print("Matriz 3x3 con valores del rango [0, 8]:")
print(matriz)

Matriz 3x3 con valores del rango [0, 8]:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Ejercicio 23

Dada la siguiente matriz, imprime las posiciones (filas y columnas) de aquellos elementos cuyo valor sea exactamente la media de toda la matriz.

In [42]:
matriz=np.array([[3,5,6],[5,4,5],[8,4,5]])

In [43]:

# Calcular la media de la matriz
media_matriz = np.mean(matriz)

# Obtener las posiciones de los elementos cuyo valor sea igual a la media de la matriz
posiciones = np.argwhere(matriz == media_matriz)

# Imprimir las posiciones
print("Posiciones de los elementos cuyo valor es la media de la matriz:")
for posicion in posiciones:
    print("Fila:", posicion[0], "- Columna:", posicion[1])


Posiciones de los elementos cuyo valor es la media de la matriz:
Fila: 0 - Columna: 1
Fila: 1 - Columna: 0
Fila: 1 - Columna: 2
Fila: 2 - Columna: 2


### Ejercicio 24

Dado el siguiente vector y el valor x, imprime el valor contenido en el vector más cercano a x.

In [ ]:
vector=np.random.permutation(np.arange(100))
x=35.4

In [44]:

# Definir el vector y el valor x
vector = np.random.permutation(np.arange(100))
x = 35.4

# Encontrar la posición del elemento más cercano a x
posicion_cercana = np.abs(vector - x).argmin()

# Imprimir la posición del elemento más cercano a x
print("Posición del elemento más cercano a", x, "en el vector:", posicion_cercana)
print("Valor en la posición encontrada:", vector[posicion_cercana])


Posición del elemento más cercano a 35.4 en el vector: 68
Valor en la posición encontrada: 35


### Ejercicio 25

Cargar la matriz de números que se encuentra en dimensiones.txt. Cada fila representa a cada uno de los objetos de un problema concreto, siendo cada una de las columnas las características que definen cada objeto. Observa que cada columna tiene un rango muy diferente. Obtener nuevas matrices en las que cada una de las características esté en la misma escala. Para cada matriz, normaliza todas las columnas utilizando uno de los siguientes métodos:
- Dividir cada elemento entre la suma de los elementos de cada columna $$\frac{x_i}{\sum_{j=1}^{n}x_j}$$
- Restar a cada elemento el mínimo de la columna y dividir entre la resta del máximo menos mínimo $$\frac{x_i-\min_j x_j}{\max_j x_j - \min_j x_j}$$
- Restar a cada elemento la media aritmética de la columna y dividir entre la desviación típica de los elementos de la columna $$\frac{x_i - \overline{x}}{\sigma}$$
- Dividir cada elemento entre la norma euclídea del vector columna $$\frac{x_i}{\sqrt{\sum_{j=1}^{n}x_j^2}}$$

In [50]:
##NORMALIZACION METODO 1##

# Cargar la matriz desde el archivo dimensions.txt
matriz = np.loadtxt("/content/dimensiones.txt", delimiter=",")

# Obtener el número de filas y columnas de la matriz
filas, columnas = matriz.shape

# Crear una nueva matriz para almacenar los resultados de la normalización
matriz_normalizada = np.zeros((filas, columnas))

# Normalizar cada columna dividiendo cada elemento por la suma de los elementos de esa columna
for j in range(columnas):
    suma_columna = np.sum(matriz[:, j])
    matriz_normalizada[:, j] = matriz[:, j] / suma_columna

# Imprimir la matriz normalizada
print("Matriz normalizada:")
print(matriz_normalizada)

Matriz normalizada:
[[ 0.00154594  0.00067639  0.00029431 -0.03193277  0.0016428   0.00105936]
 [ 0.00011214 -0.00062945  0.00139802 -0.03109244  0.00178477  0.00095852]
 [ 0.00171214  0.00098578  0.00126023 -0.03613445  0.00018253  0.00091089]
 ...
 [ 0.00186634  0.00054197  0.00022965 -0.02016807  0.00168337  0.00102793]
 [ 0.00021827  0.00097725  0.00169293  0.01596639  0.00192674  0.0010261 ]
 [ 0.00130563  0.0016387   0.00067987  0.02689076  0.00129802  0.00103341]]


In [51]:
## NORMALIZACION METODO 2##

# Cargar la matriz desde el archivo dimensions.txt, utilizando comas como delimitador
matriz = np.loadtxt("/content/dimensiones.txt", delimiter=",")

# Obtener el número de filas y columnas de la matriz
filas, columnas = matriz.shape

# Calcular el mínimo y el máximo de cada columna
minimos_columnas = np.min(matriz, axis=0)
maximos_columnas = np.max(matriz, axis=0)

# Normalizar cada columna restando el mínimo y dividiendo entre la resta del máximo menos mínimo
matriz_normalizada = (matriz - minimos_columnas) / (maximos_columnas - minimos_columnas)

# Imprimir la matriz normalizada
print("Matriz normalizada:")
print(matriz_normalizada)




Matriz normalizada:
[[0.77254509 0.43290043 0.85411247 0.12       0.80808081 0.21372607]
 [0.05511022 0.21212121 0.30588353 0.13       0.87878788 0.70916053]
 [0.85571142 0.48520924 0.37432459 0.07       0.08080808 0.9432106 ]
 ...
 [0.93286573 0.41017316 0.88623174 0.26       0.82828283 0.3681296 ]
 [0.10821643 0.48376623 0.15939564 0.69       0.94949495 0.37714286]
 [0.65230461 0.59559885 0.66259756 0.82       0.63636364 0.34120766]]


In [52]:
##METODO 3##


# Cargar la matriz desde el archivo dimensions.txt, utilizando comas como delimitador
matriz = np.loadtxt("/content/dimensiones.txt", delimiter=",")

# Obtener el número de filas y columnas de la matriz
filas, columnas = matriz.shape

# Calcular la media y la desviación estándar de cada columna
medias_columnas = np.mean(matriz, axis=0)
desviaciones_columnas = np.std(matriz, axis=0)

# Normalizar cada columna restando la media y dividiendo entre la desviación estándar
matriz_normalizada = (matriz - medias_columnas) / desviaciones_columnas

# Imprimir la matriz normalizada
print("Matriz normalizada:")
print(matriz_normalizada)



Matriz normalizada:
[[ 0.95130396 -0.23696164  1.21004216 -1.34631423  1.09540651 -0.99990004]
 [-1.54711378 -1.19316405 -0.68247725 -1.31196071  1.33734018  0.69864449]
 [ 1.24092501 -0.01041042 -0.44621456 -1.5180818  -1.39305404  1.50106035]
 ...
 [ 1.5096096  -0.33539424  1.32091982 -0.86536503  1.16453042 -0.47054389]
 [-1.36217504 -0.01666011 -1.1881623   0.61183609  1.57927384 -0.43964291]
 [ 0.53257473  0.46769078  0.54892113  1.05843178  0.50785333 -0.56284292]]


In [53]:
##METODO 4##


# Cargar la matriz desde el archivo dimensions.txt, utilizando comas como delimitador
matriz = np.loadtxt("/content/dimensiones.txt", delimiter=",")

# Calcular la norma euclidiana de cada columna
normas_columnas = np.linalg.norm(matriz, axis=0)

# Normalizar cada columna dividiendo cada elemento por la norma euclidiana correspondiente
matriz_normalizada = matriz / normas_columnas

# Imprimir la matriz normalizada
print("Matriz normalizada:")
print(matriz_normalizada)


Matriz normalizada:
[[ 0.04240074  0.01263675 -0.00803956 -0.04124698  0.04480522 -0.033441  ]
 [ 0.0030757  -0.01175975 -0.03818926 -0.04016153  0.04867727 -0.03025795]
 [ 0.04695936  0.01841696 -0.03442537 -0.04667422  0.00497836 -0.02875423]
 ...
 [ 0.05118845  0.01012534 -0.00627316 -0.02605072  0.04591152 -0.032449  ]
 [ 0.00598663  0.01825751 -0.04624533  0.02062349  0.05254933 -0.03239109]
 [ 0.03580995  0.03061521 -0.01857187  0.0347343   0.03540165 -0.03262196]]


### Ejercicio 26

En este ejercicio vamos a aproximar la integral definida de una función $\int_{a}^{b} f(x)dx$ mediante números aleatorios. Para ello, vamos a generar un conjunto de n (suficientemente grande) números aleatorios en el intervalo $[a,b]$. La aproximación de la integral de dicha función vendrá dada por

$$\frac{b-a}{n}\sum_{i=1}^{n} f(x_i).$$

Vamos a calcular la aproximación de la integral $\int_{0}^{10}f(x)dx$ donde

$$f(x)=\begin{cases}
    x^2-\frac{x}{9} & \mbox{ si } x\le 3 \\
    \frac{4x}{3}-3 & \mbox{ si } 3<x\le 6 \\
    \frac{-5x}{24}+\frac{50}{24} &  \mbox{ en otro caso}
\end{cases}$$

Evidentemente, cuanto mayor sea n (conjunto de números aleatorios), mejor será la aproximación de la integral

In [54]:

def aproximar_integral_definida(funcion, a, b, n):
    # Generar n números aleatorios en el intervalo [a, b]
    numeros_aleatorios = np.random.uniform(a, b, n)

    # Evaluar la función en cada número aleatorio generado
    evaluaciones = funcion(numeros_aleatorios)

    # Calcular la media de las evaluaciones
    media_evaluaciones = np.mean(evaluaciones)

    # Calcular la longitud del intervalo [a, b]
    longitud_intervalo = b - a

    # Aproximar la integral definida
    aproximacion_integral = longitud_intervalo * media_evaluaciones

    return aproximacion_integral

# Definir la función f(x)
def f(x):
    return x**2

# Definir el intervalo [a, b]
a = 0
b = 1

# Definir el número de puntos aleatorios
n = 10000

# Aproximar la integral definida de f(x) en [a, b]
aproximacion = aproximar_integral_definida(f, a, b, n)

print("Aproximación de la integral definida:", aproximacion)


Aproximación de la integral definida: 0.33036477620656995


In [57]:
import numpy as np

def f(x):
    if x <= 3:
        return (x**2 - x)/9
    elif 3 < x <= 6:
        return (4*x**3 - 3*x**2 - 5*x + 24)/24
    else:
        return 0

def aproximar_integral_definida(funcion, a, b, n):
    # Generar n números aleatorios en el intervalo [a, b]
    numeros_aleatorios = np.random.uniform(a, b, n)

    # Evaluar la función en cada número aleatorio generado
    evaluaciones = np.array([funcion(x) for x in numeros_aleatorios])

    # Calcular la media de las evaluaciones
    media_evaluaciones = np.mean(evaluaciones)

    # Calcular la longitud del intervalo [a, b]
    longitud_intervalo = b - a

    # Aproximar la integral definida
    aproximacion_integral = longitud_intervalo * media_evaluaciones

    return aproximacion_integral

# Definir los límites del intervalo [a, b]
a = 0
b = 10

# Definir el número de puntos aleatorios
n = 1000000  # Puedes ajustar este valor según sea necesario

# Aproximar la integral definida de f(x) en [a, b]
aproximacion = aproximar_integral_definida(f, a, b, n)

print("Aproximación de la integral definida:", aproximacion)


Aproximación de la integral definida: 43.47243088040676


### Ejercicio 27

Aproximación del número $\pi$ mediante números aleatorios.

Generar un conjunto de n puntos aleatorios de dos dimensiones en el cuadrado $[-1,1]^2$. Para cada punto aleatorio $(x_1,x_2)$, contaremos cuántos puntos satisfacen que están dentro del círculo de radio 1 centrado en $(0,0)$, es decir, cuántos cumplen la condición $x_1^2+x_2^2\le 1$. El área de dicho círculo es $\pi$, puesto que el radio es igual a 1. Por tanto, podemos establecer que

$$ \pi = 4 \frac{\mbox{# puntos dentro del círculo}}{n}$$

In [58]:

def aproximar_pi(n):
    # Generar n puntos aleatorios en el cuadrado [-1,1]^2
    puntos = np.random.uniform(-1, 1, size=(n, 2))

    # Contar cuántos puntos están dentro del círculo de radio 1 centrado en (0,0)
    puntos_dentro_circulo = np.sum(np.sum(puntos**2, axis=1) <= 1)

    # Aproximar pi
    pi_aproximado = 4 * (puntos_dentro_circulo / n)

    return pi_aproximado

# Definir el número de puntos aleatorios
n = 1000000  # Puedes ajustar este valor según sea necesario

# Aproximar pi
pi_aproximado = aproximar_pi(n)

print("Aproximación de pi:", pi_aproximado)


Aproximación de pi: 3.139592
